name: gaming_tool
description: Pro Gaming Tool UI with Shizuku
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2  # ✅ ADDED FOR SAVING UNLOCK & JSON DATA

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
